package com.manorrock.bengal.lexer;

public enum TokenType {
    IDENTIFIER, KEYWORD, NUMBER, STRING, BOOLEAN, CHARACTER, NIL,
    PLUS, MINUS, STAR, SLASH, EQUAL, NOT_EQUAL, LESS, GREATER, 
    LESS_EQUAL, GREATER_EQUAL, AND, OR, NOT,
    ASSIGN,
    LPAREN, RPAREN, LBRACE, RBRACE, COMMA, DOT, SEMICOLON,
    WHITESPACE, EOF,
    WHILE, FOR, IF, ELSE, SWITCH, CASE, DEFAULT, BREAK, CONTINUE, RETURN
}